config/routes.rb
Rforum::Application.routes.draw do
  root :to => "topics#index"

  devise_for :users
  resources :users, :only => :show

  resources :topics do
    resources :messages, :only => [:new, :create, :destroy]
  end

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :integer         not null, primary key
#  content    :text
#  user_id    :integer
#  topic_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Message < ActiveRecord::Base
  attr_accessible :content

  belongs_to :topic
  belongs_to :user

  validates_presence_of :topic_id
  validates_presence_of :user_id
  validates :content, :length => { :minimum => 3, :maximum => 1000 }

  default_scope :order => 'messages.created_at ASC'
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Topic < ActiveRecord::Base
  has_many :messages
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(128)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :messages

  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!

  def new
    @topic = Topic.find(params[:topic_id])
    @message = @topic.messages.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @message = @topic.messages.build(params[:message])
    @message.user = User.first # @wip
    if @message.save
      redirect_to topic_path(@topic)
    else
      render 'new'
    end
  end

  def destroy
    @message = current_user.messages.find params[:id]
    @message.destroy
    flash[:success] = 'Success'
    redirect_to topic_path(@message.topic)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    @messages = @topic.messages
    @title = @topic.title
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
  def title
    base_title = "Rforum"
    if @title.nil?
      base_title
    else
      "#{base_title} > #{@title}"
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <ul class="usermenu">
    <%= render 'shared/user_navigation' %>
  </ul>

  <nav class="round">
    <ul>
      <li><%= link_to "Home", topics_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
      <%= render 'shared/error_messages' %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<tr>
  <td class="message" id='<%= dom_id message %>'>
    <span class="timestamp">
      Posted <%= time_ago_in_words(message.created_at) %> ago.
    </span><br />
    <span class="content"><%= message.content %></span>

    <% if current_user && current_user == message.user %>
      <%= link_to "Delete message", [message.topic, message], :method => :delete %>
    <% end %>
  </td>
</tr>

app/views/messages/new.html.erb
<h2>Reply to the topic</h2>
<%= form_for([@topic, @message]) do |f| %>
  <%= render 'shared/form_messages', :object => f.object %>

  <div class="message_content">
    <%= f.label :content, :class => 'invisible' %>
    <%= f.text_area :content %>
  </div>
  <i>(3 chars minimum, 1000 chars maximum)</i>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
  <%- flash.each do |name, msg| -%>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  <%- end -%>

app/views/shared/_form_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %>
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_topic_menu.html.erb
  <li>
    <%= link_to('Post reply', new_topic_message_path(@topic))  %>
  </li>

app/views/shared/_user_navigation.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Sign up', new_user_registration_path)  %>
  </li>
<% end %>

app/views/topics/_topic.html.erb
<tr>
  <td class="topic">
    <%= link_to topic.title, topic %>
  </td>
</tr>

app/views/topics/index.html.erb
<h1>All topics</h1>

<table class="topics" summary="All topics">
  <%= render @topics %>
</table>

app/views/topics/show.html.erb
<table class="topic" summary="Topic thread">
  <tr>
    <td class="maintitle">
      <h1>
        <%= @topic.title %>
      </h1>
      <table class="messages" summary="Topic messages">
        <%= render @messages %>
      </table>
    </td>
  </tr>
</table>
<ul class="topicmenu">
  <%= render 'shared/topic_menu' %>
</ul>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>User: <%= @user.name %></p>